name: Update Proxy List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
permissions:
  contents: write  # This allows the workflow to push commits

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run update script
        run: python scripts/update_list.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update proxy list" || echo "No changes to commit"
          git push
